---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://127.0.0.17:1433;databasename=MybatisDB;
    username: sa 
    password: 1q2w#E$R
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    validationQuery: SELECT 1 
mybatis: 
  type-aliases-package: com.wangdh.mybatis.mapper.entity
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 10086
  context-path: /
